export { default as HeartStraight } from './HeartStraight.svg'
export { default as Globe } from './Globe.svg'
export { default as MagnifyingGlass } from './MagnifyingGlass.svg'
export { default as ShoppingBagOpen } from './ShoppingBagOpen.svg'
export { default as User } from './User.svg'
