import { Navigation } from '#components/Navigation'
import { getProductWithVariants, LocalizedProductWithVariant, products } from '#data/products'
import { serverSideTranslations } from '#i18n/serverSideTranslations'
import { withLocalePaths } from '#i18n/withLocalePaths'
import { basePath } from '#next.config'
import type { GetStaticPaths, GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import { VariantSelector as DemoStoreVariantSelector } from '#components/VariantSelector'
import { AddToCartButton, AvailabilityContainer, AvailabilityTemplate, ItemContainer, OrderContainer, OrderStorage, Price, PricesContainer } from '@commercelayer/react-components'
import { useState } from 'react'
import { useRouter } from 'next/router'
import { getLocale } from '#i18n/locale'
import { Container } from '#components/Container'
import { Header } from '#components/Header'

type Query = {
  locale: string
  code: string
}

type Props = {
  product: LocalizedProductWithVariant
}

const ProductDetailPage: NextPage<Props> = ({ product }) => {
  const [skuCode, setSkuCode] = useState<string>()
  const router = useRouter()

  const locale = getLocale(router.query.locale as string)

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={basePath + '/favicon.ico'} />
      </Head>

      <Container>
        <Header />

        <Navigation />

        <p>{product.code}</p>
        <img width="300" src={product.images[0]} alt={product.name} />
        <p>{product.name}</p>
        <p>{product.description}</p>
        <pre>{JSON.stringify(product.variant, undefined, 4)}</pre>

        <DemoStoreVariantSelector product={product} onChange={setSkuCode} />

        <OrderStorage persistKey={`country-${locale?.country?.code}`} clearWhenPlaced>
          <OrderContainer attributes={{
            language_code: locale?.language.code
          }}>
            <ItemContainer>
              <PricesContainer skuCode={skuCode}><Price /></PricesContainer>
              {/* <QuantitySelector skuCode={skuCode} /> */}

              { /** @ts-expect-error */ }
              <AddToCartButton skuCode={skuCode} buyNowMode={false} checkoutUrl='https://mm-demo-store-1.checkout-test.commercelayer.app/'>
                {
                  (props) => (
                    <button onClick={props.handleClick} disabled={props.disabled} className={`block h-10 px-6 font-semibold rounded-md ${props.disabled ? 'bg-gray-300' : 'bg-black'} text-white`}>Add to cart</button>
                  )
                }
              </AddToCartButton>

              <AvailabilityContainer skuCode={skuCode}>
                <AvailabilityTemplate />
              </AvailabilityContainer>
            </ItemContainer>
          </OrderContainer>
        </OrderStorage>
      </Container>

    </div>
  )
}

export const getStaticPaths: GetStaticPaths<Query> = () => {
  return withLocalePaths({
    paths: products.map(product => ({
      params: {
        code: product.code
      }
    })),
    fallback: false
  })
}

export const getStaticProps: GetStaticProps<Props, Query> = async ({ params }) => {
  const { code, locale } = params!

  return {
    props: {
      product: getProductWithVariants(code, locale),
      ...(await serverSideTranslations(locale))
    }
  }
}

export default ProductDetailPage
