import { Accordion } from '#components/Accordion'
import { countries, groupByRegion } from '#data/countries'
import { Link } from '#i18n/Link'
import { makeLocaleCode } from '#i18n/locale'
import { basePath } from '#next.config'
import { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Commerce Layer | Demo Store</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href={basePath + '/favicon.ico'} />
      </Head>

      <div className='container mx-auto px-6'>
        <div className='py-6 pb-6 border-b border-b-gray-100'>
          <img src={basePath + '/commercelayer.svg'} width='32' />
        </div>

        <div className='py-12 pb-12 font-extrabold'>
          CHOOSE YOUR COUNTRY/REGION
        </div>

        <div className='border-b border-gray-400'>
          {
            // Country Selector
            Object.entries(groupByRegion(countries)).map(([regionName, countries]) => (
              <Accordion title={<div className='font-extrabold'>{regionName.toUpperCase()}</div>} content={(
                <div>
                  {
                    countries.map(country => (
                      <Link locale={makeLocaleCode(country.code, country.default_language)}>
                        <a className='py-6 border-t border-t-gray-100 font-semibold block'>{country.name}</a>
                      </Link>
                    ))
                  }
                </div>
              )} />
            ))
          }
        </div>
      </div>

      <div className='bg-gray-50 border-t border-gray-200 mt-12 pt-6 pb-6'>
        <div className='container mx-auto px-6'>
          Other Countries / Regions:
          <Link locale='en'>
            <a className='font-semibold block'>International (English)</a>
          </Link>
        </div>
      </div>

    </div>
  )
}

export default Home
