import { Navigation } from '#components/Navigation'
import { getProductWithVariants, LocalizedProductWithVariant, products } from '#data/products'
import { serverSideTranslations } from '#i18n/serverSideTranslations'
import { withLocalePaths } from '#i18n/withLocalePaths'
import { basePath } from '#next.config'
import type { GetStaticPaths, GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import { VariantSelector } from '#components/VariantSelector'


type Query = {
  locale: string
  code: string
}

type Props = {
  product: LocalizedProductWithVariant
}

const ProductDetailPage: NextPage<Props> = ({ product }) => {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={basePath + '/favicon.ico'} />
      </Head>

      <Navigation />

      <p>{product.code}</p>
      <img width="300" src={product.primaryImage} alt={product.name} />
      <p>{product.name}</p>
      <p>{product.description}</p>
      <pre>{JSON.stringify(product.variant, undefined, 4)}</pre>

      <VariantSelector product={product} />
    </div>
  )
}

export const getStaticPaths: GetStaticPaths<Query> = () => {
  return withLocalePaths({
    paths: products.map(product => ({
      params: {
        code: product.code
      }
    })),
    fallback: false
  })
}

export const getStaticProps: GetStaticProps<Props, Query> = async ({ params }) => {
  const { code, locale } = params!

  return {
    props: {
      product: getProductWithVariants(code, locale),
      ...(await serverSideTranslations(locale))
    }
  }
}

export default ProductDetailPage
