import { Navigation } from '#components/Navigation'
import { Link } from '#i18n/Link'
import { serverSideTranslations } from '#i18n/serverSideTranslations'
import { withLocalePaths } from '#i18n/withLocalePaths'
import { basePath } from '#next.config'
import type { GetStaticPaths, GetStaticProps, NextPage } from 'next'
import Head from 'next/head'

import skus from '../../../../tmp/skus.json'

type Query = {
  locale: string
}

type Props = {
  products: (typeof skus)[number][]
}

const Home: NextPage<Props> = ({ products }) => {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={basePath + '/favicon.ico'} />
      </Head>

      <Navigation />

      {
        products.map(product => (
          <div key={product.code}>
            <Link href={`/products/${product.code}`} >{product.name}</Link>
          </div>
        ))
      }
    </div>
  )
}

export const getStaticPaths: GetStaticPaths<Query> = () => {
  return withLocalePaths({
    paths: [],
    fallback: false
  })
}

export const getStaticProps: GetStaticProps<Props, Query> = async ({ params }) => {
  return {
    props: {
      products: skus,
      ...(await serverSideTranslations(params?.locale!))
    }
  }
}

export default Home
