import { Navigation } from '#components/Navigation'
import { Link } from '#i18n/Link'
import { serverSideTranslations } from '#i18n/serverSideTranslations'
import { withLocalePaths } from '#i18n/withLocalePaths'
import { basePath } from '#next.config'
import type { GetStaticPaths, GetStaticProps, NextPage } from 'next'
import Head from 'next/head'

import { getProductByCode, LocalizedProduct } from '#data/products'

type Query = {
  locale: string
}

type Props = {
  products: LocalizedProduct[]
}

const Home: NextPage<Props> = ({ products }) => {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={basePath + '/favicon.ico'} />
      </Head>

      <Navigation />

      {
        products.map(product => (
          <div key={product.code} className="flex items-center gap-4 my-6">
            <img src={product.primaryImage} alt={product.name} width="60" />
            {product.code.split(/^(\w{8})(\w{6})(\w{6})(\w{4})$/).join(' ')}
            <Link href={`/products/${product.code}`} >{product.name}</Link>
          </div>
        ))
      }
    </div>
  )
}

export const getStaticPaths: GetStaticPaths<Query> = () => {
  return withLocalePaths({
    paths: [],
    fallback: false
  })
}

export const getStaticProps: GetStaticProps<Props, Query> = async ({ params }) => {
  const { locale } = params!

  return {
    props: {
      products: [
        getProductByCode('BOTT17OZFFFFFF000000XXXX', locale),
        getProductByCode('BODYBSSSFFFFFF0000006MXX', locale),
        getProductByCode('BODYBSSS000000FFFFFF12MX', locale),
        getProductByCode('CUFFBEANFFFFFF000000XXXX', locale)
      ],
      ...(await serverSideTranslations(locale))
    }
  }
}

export default Home
